export const types = {
    FETCH_ADVENTURES_STARTED: 'FETCHING_ADVENTURES',
    FETCH_ADVENTURES_SUCCESS: 'FETCHING_ADVENTURES_SUCCESS',
    FETCH_ADVENTURES_FAILURE: 'FETCHING_ADVENTURES_FAILURE',
  };
  